#!/bin/bash

shutdown="⏻ Shutdown"
reboot="󰜉 Reboot"
logout=" Logout"

list_col=1
list_row=3
general_style="$HOME/.config/rofi/launchers/type-4/style-1.rasi"

msg="$(hostname)"
rofi_cmd() {
  rofi $1 \
    -mesg $msg \
    -theme "${general_style}" \
    -theme-str 'mainbox{children: [ "message", "listview" ];}' \
    -theme-str "listview {columns: $list_col; lines: $list_row;}" \
    -theme-str "window {width: 400;}"
}

run_rofi() {
  echo -e "$shutdown\n$reboot\n$logout" | rofi_cmd "-dmenu"
}

choise=$(run_rofi)
if [[ "$choise" == "$shutdown" ]]; then
  /bin/shutdown now

elif [[ "$choise" == "$reboot" ]]; then
  /bin/reboot now

elif [[ "$choise" == "$logout" ]]; then
  if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then
    /bin/killall Hyprland
  elif [[ "$XDG_CURRENT_DESKTOP" == "openbox" ]]; then
    /bin/openbox --exit
  fi
fi

