#!/bin/bash

opt1="⏻ Apagar"
opt2="󰜉 Reiniciar"
opt3="󰿅 Salir de la sesión"

list_col=1
list_row=3
general_style="$HOME/.config/rofi/launchers/type-4/style-1.rasi"

msg="$(hostname)"
rofi_cmd() {
  rofi $1 \
    -mesg $msg \
    -theme "${general_style}" \
    -theme-str "listview {columns: $list_col; lines: $list_row;}" \
    -theme-str "inputbar {enabled: false;}"
}

run_rofi() {
  echo -e "$opt1\n$opt2\n$opt3" | rofi_cmd "-dmenu"
}

choise=$(run_rofi)
if [[ "$choise" == "$opt1" ]]; then
  /bin/shutdown now

elif [[ "$choise" == "$opt2" ]]; then
  /bin/reboot now

elif [[ "$choise" == "$opt3" ]]; then
  if [[ "$XDG_CURRENT_DESKTOP" == "Hyprland" ]]; then
    /bin/killall Hyprland
  elif [[ "$XDG_CURRENT_DESKTOP" == "openbox" ]]; then
    /bin/openbox --exit
  fi
fi

